import {container, aside, header, footer, main, Menu, Submenu, MenuItem, Icon, Button, ButtonGroup, Input , Select, Option, DatePicker , scrollbar, Row,Drawer,
  Col, Card, Table, TableColumn, Pagination, Tooltip, Popover, Popconfirm, Message, Form,
  FormItem, Radio, RadioGroup, Checkbox, CheckboxGroup, Dialog, Upload, Transfer, Progress, Tabs, TabPane, Calendar,
  Dropdown, DropdownMenu, DropdownItem, Divider, Collapse, CollapseItem, Alert, Badge, Switch, Steps,Step,} from 'element-ui'

export const elementWzp = {
  container,
  aside,
  header,
  footer,
  main,
  Menu,
  Submenu,
  MenuItem,
  Icon,
  scrollbar,
  Row,
  Col,
  Card,
  Button,
  Input,
  Select,
  Option,
  DatePicker,
  Drawer,
  Pagination,
  Table,
  TableColumn,
  Tooltip,
  Popover,
  Popconfirm,
  Message,
  Form,
  FormItem,
  Radio,
  RadioGroup,
  Checkbox,
  CheckboxGroup,
  Dialog,
  Upload,
  Progress,
  Transfer,
  Tabs,
  TabPane,
  Calendar,
  Dropdown,
  DropdownMenu,
  DropdownItem,
  ButtonGroup,
  Divider,
  Collapse,
  CollapseItem,
  Alert,
  Badge,
  Switch,
  Steps,
  Step,
}
